import asyncio
from src.ingestion.registry import registry
from src.utils.logger import logger
from src.db.schema import init_db, async_session, EventModel
import json

async def run_ingestion():
    logger.info("Starting ingestion cycle...")
    await init_db()
    
    adapters = registry.get_all_active()
    if not adapters:
        logger.warning("No active adapters found.")
        return
        
    for adapter in adapters:
        logger.info(f"Running adapter: {adapter.name}")
        raw_data = await adapter.fetch_data()
        events = adapter.normalize_events(raw_data)
        
        if not events:
            logger.warning(f"No events generated by {adapter.name}")
            continue
            
        async with async_session() as session:
            for event in events:
                db_event = EventModel(
                    event_type=event.event_type,
                    chain=event.chain,
                    asset=event.asset,
                    timestamp=event.timestamp.replace(tzinfo=None),
                    source=event.source,
                    raw_reference=event.raw_reference,
                    metadata_json=event.metadata
                )
                session.add(db_event)
            await session.commit()
            logger.info(f"Persisted {len(events)} events from {adapter.name}")

    await registry.close_all()
    logger.info("Ingestion cycle complete.")

if __name__ == "__main__":
    asyncio.run(run_ingestion())
